spring:
  application:
    name: infra-orders-service
  config:
    import: "configserver:"
  profiles:
    active: dev #prod
  cloud:
    config:
      uri: http://localhost:8888  #http://localhost:8888 - http://infra-config-server:8888